version: '3.0'
services:
  aws-cli:
    image: vuba/aws-cli:0.0.1
    build:
      context: .
    volumes:
      - type: volume
        source: aws-credentials
        target: /.aws

volumes:
  aws-credentials:
